### ISSUE TITLE
Donation platform integration

### ISSUE THREAD

**Issue by mwillmott** [Techbikers/techbikers#1]
We need to integrate a donation platform with the Techbikers site to allow our riders to fundraise for any given ride and allow us to track fundraising. The idea of integration is that we want to minimise the amount of form filling and setup on other sites as well as being able to display fundraising info on our site. Last year we used Believe.in but they have since shut down.

We are currently looking at integrating with ~~Givey (givey.com)~~ Just Giving. There are several key areas i see that we can integrate. We are pressed for time so they don't all need to be done and we should figure out what can be done quickly and what should be done first.
- [x] ~~Add a field(s) to the rider model so we know if and the details of their fundraising profile on Givey. This is likely to just be the Givey UID.~~ _We have added the fundraiser model (see dae95df1014514837e6bba62c569b365e5f03431) which links the user and ride to a fundraising page on JG_
- [x] Link through to the donation page from the rider profile. ~~Either users go and manually create their accounts and we enter their Givey UID into the system so we can link through or we create their accounts through the Givey API. This should be pretty easy.~~ _We have replaced the donation_page field in the rider model and now fetch the JG page from the fundraising record_
- [x] Figure out how fundraising relates to an individual ride. ~~Unlike Virgin Giving, Givey doesn't have the concept of events. You can donate against a bit of content though – i'd suggest we use the ride page url for this so we can track donations against the ride.~~ _JG have events so all fundraising pages are created against an event which matches the ride._
- [ ] Display how much an individual has raised for any given ride
- [ ] Display how much has been raised in total for a ride
- [ ] Show a leaderboard for each ride

The last points i'm not sure how much caching and storing of fundraising info on our side we want to do. Let's not pre-emptively optimise though – i'm happy to hammer the API each time for now ;)

The most important thing is getting the riders donation setup so they can start to fundraise.

**Comment by mwillmott** [comment]
An overview of the Givey API and how it could work with the above (from @marcqualie – CTO):

- create user
  I can enable this endpoint for you later today

- create first piece of content (yes this is how fundraisers work)
  This requires a bit of manual work on the part of each rider currently. A fundraising page is generated after the first donation to a piece of content by a user. Once they’ve made their donation a URL is generated https://www.givey.com/s/:content_url/u/:username where others can go to view their progress (although they’ll probably browse this on your site). The limitation here is that in order to “inspire” someone, i.e. have them donate through your account, is that there needs to be a donation in the system first to start the chain. I understand this may be slightly troublesome to automate but it’s a decision we made a company in order to connect the dots in our system based on donation networking. You can follow the steps below after creating the users and content to email each rider with their own pre=built link in order to donate (£1.05 minimum) and get their page generated. They will need to be logged in with the correct username in order to do so.

- The URL is constructed at this endpoint https://www.givey.com/share with the following params:
  - charity_id: giveytag of the charity to preselect (optional, can be modified by the user)
  - amount: suggested amount (optional, can be modified by the user)
  - url: The url to the piece of content they’re donating to (optional, won’t be linked to the correct content without)
  - inspired_by: username of the rider they’re donating because of (optional, won’t be linked to a rider without)
  - client_id: your application token (required)
  - redirect_to: where you want donors to end up after successful donation

- Get the total amount raised per rider
  - Request /donations?user_id={username}&content_id={content_id} will return all donations inspired by a rider to that piece of content. I can addd a field to the meta data containing various information like the sum and counts so you don’t have to iterate over these manually.

**Comment by mwillmott** [comment]
With the release at 5cbe257337e8163a05fcf140657da3e5b47d16f8, we have now got the fundraising system up and running. Users can provide their Just Giving credentials and we will create fundraising pages with all the required details. There are certainly improvements that can be made, especially around error handling/reporting. Currently, if anything goes wrong in this process the page will just hang and not show the user anything useful, even if it's something simple like their JS credentials are wrong.

Next steps are to pull fundraising info into our site and display it on the ride/user pages.

**Comment by marcqualie** [comment]
Hey @mwillmott, just saw this thread. Based on your last message, does that mean you will not be integrating with the Givey API?

**Comment by mwillmott** [comment]
@marcqualie not this time i'm afraid. We looked at trying to get it to work but the Givey API just didn't quite fit our needs right now and we needed to get this done quickly. We'll be using Just Giving for at least this ride but we're very happy to switch across to Givey for the future. Might be worth you keeping an eye on this thread/repo so you know what our requirements are and seeing if it fits in with any of your plans over at Givey.

**Comment by mwillmott** [comment]
Putting together a quick leaderboard for a ride should be pretty easy using this API: https://api.justgiving.com/docs/resources/v1/Leaderboard/GetEventLeaderboard

**Comment by pawelsawicz** [comment]
Heya, if you have any questions about JustGiving API let me know :)

**Comment by mwillmott** [comment]
I certainly do @pawelsawicz! I've been working on moving this integration over to your brand new OAuth implementation (rather than asking for credentials which seems to be buggy and is causing us issues). I can't for the life of me figure out how to get ahold of our secret key though.

**Comment by pawelsawicz** [comment]
@mwillmott ah yes I sent you email about secret key.

**Comment by mwillmott** [comment]
@pawelsawicz nothing received yet. Can you send to mwillmott [at] gmail.com
