### ISSUE TITLE
Editing of rider profile

### ISSUE THREAD

**Issue by mwillmott** [Techbikers/techbikers#2]
Users can't currently edit their rider profile pages. We should get this sorted soon.

**Comment by mwillmott** [comment]
As part of this, we need to let users upload their own avatar image. At the moment we just use Gravatar and not many users seem to be making use of this.

**Comment by tfm** [comment]
I'd like to help out on the site, and given my Twitter handle has an extra "@" on techbikers.com, this seems like a good issue to get my hands dirty with; I'll take a look.
