### ISSUE TITLE
Actually show a users past rides on their account page

### ISSUE THREAD

**Issue by mwillmott** [Techbikers/techbikers#7]
Currently we just list all the rides instead of the actual rides a user has been on. Not sure why, probably because i wanted a placeholder while i was writing the account page and never got around to sorting this out.

**Comment by Dremora** [comment]
This is probably not required anymore as the account page will only display editable user data, relying on the profile page for the rides. Unless you think it still makes sense.

**Comment by mwillmott** [comment]
Yeah, these issues are super old. I'm just going to close them and we'll keep using Trello.
